### ISSUE TITLE
Dodo emoji not available on Windows

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/mdx-bundler#1]
I'm afraid the [dodo emoji](https://emojipedia.org/dodo/) used in the About section of this repo is not available on Windows 10 yet:

![image](https://user-images.githubusercontent.com/1087670/107872698-4d956a00-6eac-11eb-930b-a9f02b6b2154.png)

**Comment by kentcdodds** [comment]
Bummer... I think I'll just leave it though 🤷‍♂️ It's not that important and other platforms will catch up eventually.

**Comment by pomber** [comment]
Same in Linux
![image](https://user-images.githubusercontent.com/1911623/111252638-52a32180-85f0-11eb-9b40-87e2a0fb54ab.png)

**Comment by kentcdodds** [comment]
It doesn't matter that much and eventually it'll work for everyone so I'm not going to worry about it...

**Comment by Arcath** [comment]
Windows 11 now supports the dodo emoji 🦤!
