### ISSUE TITLE
`bundleMDX` returns 

### ISSUE THREAD

**Issue by gr-qft** [kentcdodds/mdx-bundler#105]
Thanks for this awesome library! 

I have a question. Currently `bundleMDX` return `frontmatter`, `code`, and `matter`, but it would be really useful in some cases to have access to the parsed objects from remark and rehype. If I need those objects now, it seems the only way is run remark and rehype again outside of  `bundleMDX`. 

Could you guys add these parsed objects ? 

Thanks!

**Comment by Arcath** [comment]
I don't think we can. the mdx compiling is done inside the xdm esbuild plugin and our only interaction is with the completed bundle.

What are you trying to access? would it be possible to throw in your own remark/rehype plugin to extract the data?

**Comment by gr-qft** [comment]
I see... Yes, that's what I'm trying to do, just writing a rehype plugin to extract some document data that I need. 

Thanks!
