### ISSUE TITLE
Allow accessing named exports from mdx

### ISSUE THREAD

**Issue by xoumi** [kentcdodds/mdx-bundler#108]
- `mdx-bundler` version: 6.0.2
- `node` version: 16.6.2
- `npm` version: 7.20.6

**Problem description**: After seeing [this](https://github.com/kentcdodds/mdx-bundler/issues/98) issue I started working on a mdx remark plugin to extract headings from a mdx file and export it as a named constant but realized that `mdx-bundler` only exposes the component default export. There are a few existing mdx remark plugins that do something similar such as  [remark-mdx-metadata](https://github.com/manovotny/remark-mdx-metadata) which also get affected by this.

**Suggested solution**: Return `Component` instead of `Component.default`. This would be a breaking change, thus wanted to discuss other possible solutions before raising a PR for the same.

**Comment by xoumi** [comment]
Opted for moving the `.default` to the client side functions as I felt exporting two possibly large strings could feel heavy. Have a look :) @Arcath

**Comment by Zemnmez** [comment]
@xoumi did you end up writing that plugin? Can I take a look?
