### ISSUE TITLE
Error building on Netlify with Next JS

### ISSUE THREAD

**Issue by sarimabbas** [kentcdodds/mdx-bundler#113]
## Versions

Hello and thank you for making this library! I am having some trouble building on Netlify with my NextJS project and wanted to request your help. My details are: 

- `mdx-bundler` version: 6.0.2
- `node` version: 16.11.1
- `yarn` version: 1.22.10
- `esbuild` version: 0.13.5
- `Next.js` version: 11.1.2
- `webpack` version: 5

## Relevant code or config

```ts
// mdx code

const bundleMdxFileWrapper = (filePath: string) => {
  if (process.platform === "win32") {
    process.env.ESBUILD_BINARY_PATH = path.join(
      process.cwd(),
      "node_modules",
      "esbuild",
      "esbuild.exe"
    );
  } else {
    process.env.ESBUILD_BINARY_PATH = path.join(
      process.cwd(),
      "node_modules",
      "esbuild",
      "bin",
      "esbuild"
    );
  }

  return bundleMDXFile(filePath, {
    xdmOptions: (options) => {
      options.remarkPlugins = [
        ...(options.remarkPlugins ?? []),
        remarkMdxImages,
      ];
      return options;
    },
    esbuildOptions: (options) => {
      // Set the `outdir` to a public location for this bundle.
      options.outdir = COPY_IMAGES_PATH;
      options.loader = {
        ...options.loader,
        // Tell esbuild to use the `file` loader for pngs
        ".png": "file",
      };
      // Set the public path
      options.publicPath = "/images/things";

      // Set write to true so that esbuild will output the files.
      options.write = true;

      return options;
    },
  });
};
```

```js
// next.config.js
module.exports = {
  reactStrictMode: true,
};
```

## What you did:

I have MDX bundler set up as above. I call it inside `getStaticProps` to pre-render list-view and item-view pages. Everything works fine building locally, but there is some trouble with `esbuild` when deploying on Netlify.

## What happened:

```
10:01:34 AM: (node:1799) [DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API
10:01:34 AM: (Use `node --trace-deprecation ...` to show where the warning was created)
10:01:34 AM: (node:1799) [DEP_WEBPACK_CHUNK_ADD_MODULE] DeprecationWarning: Chunk.addModule: Use new ChunkGraph API
10:01:39 AM: Failed to compile.
10:01:39 AM: 
10:01:39 AM: ./node_modules/esbuild/lib/main.d.ts
10:01:39 AM: Module parse failed: Unexpected token (1:7)
10:01:39 AM: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
10:01:39 AM: > export type Platform = 'browser' | 'node' | 'neutral';
10:01:39 AM: | export type Format = 'iife' | 'cjs' | 'esm';
10:01:39 AM: | export type Loader = 'js' | 'jsx' | 'ts' | 'tsx' | 'css' | 'json' | 'text' | 'base64' | 'file' | 'dataurl' | 'binary' | 'default';
10:01:39 AM: > Build error occurred
10:01:39 AM: Error: > Build failed because of webpack errors
10:01:39 AM:     at /opt/build/repo/node_modules/next/dist/build/index.js:397:19
10:01:39 AM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:60:20)
10:01:39 AM:     at async Object.build [as default] (/opt/build/repo/node_modules/next/dist/build/index.js:77:25)
10:01:39 AM: error Command failed with exit code 1.
10:01:39 AM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:01:39 AM: ​
10:01:39 AM: ────────────────────────────────────────────────────────────────
10:01:39 AM:   "build.command" failed                                        
10:01:39 AM: ────────────────────────────────────────────────────────────────
```

Would appreciate any thoughts or suggestions, thank you!

**Comment by Arcath** [comment]
Further testing on this I've got 0.13.6 to build if I delete `main.d.ts` from its folder, not sure why next is getting hung up on a .d.ts inside node_modules but I'll keep going.

The other thing of note is that 0.13.x now sees itself being bundled and throws an error. To solve this you have to import `mdx-bunder` _after_ you set `ESBUILD_BINARY_PATH` like so `const {bundleMDX} = await import('mdx-bundler')`.

Once I get it working without messing with the contents of node_modules I'll update the docs.

**Comment by Arcath** [comment]
Ok I got this working :)

So I had to add `esbuild-loader` to my webpack config to fix the compilation error.

https://github.com/Arcath/arcath.net-next/blob/main/next.config.js#L11-L22

And then make the patch I mentioned earlier by importing mdx-bundler after I set the binary path

https://github.com/Arcath/arcath.net-next/blob/main/lib/functions/prepare-mdx.ts#L59

**Comment by sarimabbas** [comment]
Sweet thank you! I'll give this a try

**Comment by ctrlaltdylan** [comment]
@Arcath can you elaborate on the value of `ESBUILD_BINARY_PATH`? I can follow everything else in code but the `.env` isn't present.
