### ISSUE TITLE
Migrate to MDX v2

### ISSUE THREAD

**Issue by dstroot** [kentcdodds/mdx-bundler#137]
Not sure where to ask questions - what is the roadmap or plans for MDX v2?  Cheers!

**Comment by biowaffeln** [comment]
It would probably make sense to switch back to using `@mdx-js/mdx` instead of `xdm`, since the two projects have merged again and the former is the one that is being maintained. [^1]

[^1]: https://github.com/wooorm/xdm/issues/94#issuecomment-948687452

**Comment by beaussan** [comment]
Since the v2 of mdx officially launched, is there a plan to migrate to it?

**Comment by kentcdodds** [comment]
Yes, we should migrate. Hopefully it's pretty simple/minimal.

**Comment by kentcdodds** [comment]
To be clear, I don't have the bandwidth to do this, but I would be willing to look at a PR for it.
