### ISSUE TITLE
Module not found: jsx runtime fails to load with Preact

### ISSUE THREAD

**Issue by oedotme** [kentcdodds/mdx-bundler#140]
- `mdx-bundler` version: 8.0.1
- `next` version: 12.0.7
- `preact` version: 10.6.4
- `node` version: 17.3.0
- `pnpm` version: 6.25.1

## What you did:
Upgraded `preact` from 10.5.15 to 10.6.4

## What happened:
```shell
Module not found: Package path ./compat/jsx-runtime.js is not exported from package /.../node_modules/preact
(see exports field in /.../node_modules/preact/package.json)
```

## Problem description:
`mdx-bundler` couldn't find `react/jsx-runtime.js` module as its alias `compat/jsx-runtime.js` fails to load. However `compat/jsx-runtime` _without .js extension_ is already exported from `preact/package.json` exports field.

## Suggested solution:
Just by omitting the .js extension from `react/jsx-runtime.js` import at [**mdx-bundler/src/client.js**](https://github.com/kentcdodds/mdx-bundler/blob/main/src/client.js) (line 2):
```ts
 import * as _jsx_runtime from 'react/jsx-runtime.js'
```
To be updated as:
```ts
 import * as _jsx_runtime from 'react/jsx-runtime'
```

**Comment by aktschge** [comment]
There is a temporary work-around for this issue. Just map the aliases correctly, until it is fixed.
This works for me with `"preact": "^10.6.4"`:

```js
// next.config.js
module.exports = {
  reactStrictMode: true,

  webpack: (config, { dev, isServer }) => {
    // Replace React with Preact only in client production build
    if (!dev && !isServer) {
      Object.assign(config.resolve.alias, {
        'react/jsx-runtime.js': 'preact/compat/jsx-runtime',
        react: 'preact/compat',
        'react-dom': 'preact/compat',
        'react-dom/test-utils': 'preact/test-utils',
      });
    }

    return config;
  },
};
```


Source: https://github.com/contentlayerdev/contentlayer/issues/62#issuecomment-986982643

**Comment by oedotme** [comment]
This workaround works. Thanks a lot for your comment!

> Object.assign(config.resolve.alias, {
> 'react/jsx-runtime.js': 'preact/compat/jsx-runtime',

I'm not sure if that should be handled at the `preact` package or here at `mdx-bundler`.

I tried omitting the `.js` extension as suggested above and it solves the problem, but it breaks `uvu` tests because of this missing `.js` and seems related to ESM.

**Comment by oedotme** [comment]
This workaround works. Thanks a lot for your comment!

> Object.assign(config.resolve.alias, {
> 'react/jsx-runtime.js': 'preact/compat/jsx-runtime',

I'm not sure if that should be handled at the `preact` package or here at `mdx-bundler`.

I tried omitting the `.js` extension as suggested above and it solves the problem, but it breaks `uvu` tests because of the missing `.js` and seems related to ESM.

**Comment by oedotme** [comment]
`mdx-bundler` version `9.0.0` is now released with support for React 18.

`react/jsx-runtime` import was updated omitting the `.js` extension which fixes this issue.
