### ISSUE TITLE
TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by GoodluckH** [kentcdodds/mdx-bundler#142]
- `mdx-bundler` version: 8.0.1
- `node` version: 14.16
- `npm` version: 7.11.1

Relevant code or config
package.json
```js
{
  "name": "personal",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@mdx-js/loader": "^0.15.4",
    "@next/mdx": "^12.0.7",
    "esbuild": "^0.14.11",
    "mdx-bundler": "^8.0.1",
    "next": "12.0.7",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "rehype-prism": "^1.0.0",
    "remark-gfm": "^3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.2",
    "eslint": "8.6.0",
    "eslint-config-next": "12.0.7",
    "postcss": "^8.4.5",
    "tailwindcss": "^3.0.12"
  }
}

```

## What you did:
I was using the bundler for a nextjs project. And, to set up the `[id].js` as per nextjs [tutorial](https://nextjs.org/learn/basics/dynamic-routes/page-path-external-data), I did the following to render my mkdown posts:
```js
import { getMDXComponent } from "mdx-bundler/client";
import { useMemo } from "react";
import { getAllPostIds, getPostData } from "../../util/posts";

export async function getStaticProps({ params }) {
 /* same as nextjs tutorial */
}

export async function getStaticPaths() {
 /* same as nextjs tutorial */
}

export default function BlogPost({ code, frontmatter }) {
  const Component = useMemo(() => getMDXComponent(code), [code]);

  return (
    <>
      <h1>{frontmatter.title}</h1>
      <p>{frontmatter.description}</p>
      {/* <p>{frontmatter.date}</p> */}
      <article>
        <Component />
      </article>
    </>
  );
}

```

## What happened:

Got an error `TypeError: Cannot read property 'default' of undefined` when checking out the post page.

![Screen Shot 2022-01-11 at 10 32 23 PM](https://user-images.githubusercontent.com/23110002/149059160-7477428d-99f0-4894-99b0-a6c4797b2944.png)

**Comment by charlsyang** [comment]
@GoodluckH Hi, I’m having this exact same issue, may I ask how did you resolve it? Couldn’t wrap my head around what went wrong

**Comment by GoodluckH** [comment]
@charlsyang I had some typos in other parts of the codebase. This error code is terrible, though.

**Comment by charlsyang** [comment]
@GoodluckH Oh I figured it out, in my case I missed the spread syntax `...` and didn’t expand the returned `postData` props within the `getStaticProps`. Though still not sure why I need to do that (I am super new to JS). Still, thanks for replying!

``` js
export async function getStaticProps({ params }) {
    const postData = await getPostData(params.id)
    return {
        props: {
            ...postData // missed `...` here
        }
    }
}
```

**Comment by GoodluckH** [comment]
@charlsyang lmfao that's exactly how I got it wrong
