### ISSUE TITLE
useContext is not working as expected

### ISSUE THREAD

**Issue by jacargentina** [kentcdodds/mdx-bundler#144]
https://github.com/jacargentina/remix-mdx-test

<img width="422" alt="Captura de Pantalla 2022-01-12 a la(s) 21 56 07" src="https://user-images.githubusercontent.com/517228/149246710-8d354653-c19f-41d4-b115-24e41b735438.png">

@kentcdodds as promised, here is the demo for the `useContext` problem, as I pointed on discord today.

Cheers!

**UPDATE**: added a commit with a *hackish*? way to solve it. I hope there is a better approach?

<img width="409" alt="Captura de Pantalla 2022-01-13 a la(s) 14 48 13" src="https://user-images.githubusercontent.com/517228/149382391-805d5672-3990-4b5d-80bd-323c951b11e6.png">

**Comment by jacargentina** [comment]
**SOLVED**

The mdx "server-side" source, should have the normal "tree" with its own context provider!

The example repo has the commit with the needed modifications.

**Comment by aliceHendicott** [comment]
Hey @jacargentina, did you ever find a better way to solve this issue? 
I'm encountering something similar when using `styled-components` that reference a theme context and don't think it can be solved by exposing the theme globally unless we also change all the references to that theme.
