### ISSUE TITLE
React 18 error: "./jsx-runtime.js is not exported from package"

### ISSUE THREAD

**Issue by dstroot** [kentcdodds/mdx-bundler#164]
- `mdx-bundler` version: ^8.0.1
- `node` version: 16.14.2
- `npm` version: 8.5

Relevant code or config

- N/A

What you did:

I upgraded to React 18 from 17.0.2

What happened:

NOTE: Also using Next.js version 12.1.2. When I run "build" after upgrading react from 17.0.2 to 18.0 I get the error below:

---
./node_modules/mdx-bundler/dist/client.js
Module not found: Package path ./jsx-runtime.js is not exported from package /Volumes/T7/Code/blog-next/node_modules/react (see exports field in /Volumes/T7/Code/blog-next/node_modules/react/package.json)

Import trace for requested module:
./node_modules/mdx-bundler/client/index.js
./pages/snippets/[slug].jsx

---

Reproduction repository:

Problem description:

React 18 seems to introduce a problem with how jsx-runtime is consumed from React.  MDX-Bundler pull request #162 may address this issue already.  I am not sure.  

Suggested solution:

Maybe test React 18 with Pull Request 162?
Also see similar issue here: https://github.com/hashicorp/next-mdx-remote/pull/250

**Comment by schickling** [comment]
I was facing the same problem with Contentlayer and found a workaround/solution that works for Next.js:

[](https://user-images.githubusercontent.com/1567498/160865407-814e3bb8-23b7-4ab9-9488-d71697c96f5b.png)https://user-images.githubusercontent.com/1567498/160865407-814e3bb8-23b7-4ab9-9488-d71697c96f5b.png

**Comment by dstroot** [comment]
@schickling - you rock!  Can confirm with a couple twists.  First, it didn't work if I had ".js" at the end my require().  Mine works like this:
<img width="916" alt="Screen Shot 2022-03-30 at 5 15 45 PM" src="https://user-images.githubusercontent.com/1438457/160951477-69058ed6-3505-4a6b-9bdb-35e6cd73261f.png">

Second, I needed to now import React and ReactDOM, not typically needed in a Nextjs project:
<img width="916" alt="Screen Shot 2022-03-30 at 5 16 51 PM" src="https://user-images.githubusercontent.com/1438457/160951582-2d7d3d38-0095-4cd2-b4f9-ec1df4a3cd3f.png">

After that I can build successfully with React 18.

**Comment by jamesthesken** [comment]
Thank you both for posting those workarounds!

For some reason it is not working as expected on my end. Even with a similar setup as @dstroot.

Did you have to install jsx-runtime through npm?

**Comment by dstroot** [comment]
@jamesthesken - you do not need to install jsx-runtime.  It comes with React, although the issue seems to be that React doesn't export it, or rather exports it as jsx_runtime, not jxs_runtime.js.

**Comment by FradSer** [comment]
#167 LGTM, upgrade to v9.0.0 works.

**Comment by dstroot** [comment]
Yes, v9.0.0 fixes the issue.  Closing.
