### ISSUE TITLE
Module not found: Can't resolve 'builtin-modules'

### ISSUE THREAD

**Issue by rockchalkwushock** [kentcdodds/mdx-bundler#18]
- `mdx-bundler` version: 3.1.2
- `node` version: 14.15.4
- `yarn` version: 1.22.10
- `next` version: 10.1.3 & 10.0.9

Relevant code or config

```js
// config for 10.1.3
module.exports = {
  future: {
    webpack5: true,
  },
  reactStrictMode: true,
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    if (!isServer) {
      // https://github.com/vercel/next.js/issues/7755
      config.resolve = {
        ...config.resolve,
        fallback: {
          ...config.resolve.fallback,
          // Don't load this on the client.
          fs: false,
        },
      }
    }

    return config
  },
}

// config for 10.0.9
module.exports = {
  reactStrictMode: true,
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    if (!isServer) {
      // https://github.com/vercel/next.js/issues/7755
      config.node = {
        // Don't load this on the client.
        fs: 'empty',
      }
    }

    return config
  },
}
```

What you did:

Following along with the documentation and after installing `mdx-bundler` and trying to run the dev sever for `next` I get the below output. The other screen shot is the output from executing `yarn build` I get the same using either version and configuration of `next`.

What happened:

<img width="1440" alt="Screen Shot 2021-04-05 at 10 33 43" src="https://user-images.githubusercontent.com/19720404/113592684-1402f480-95fb-11eb-8610-5d6368451cc5.png">

<img width="1943" alt="Screen Shot 2021-04-05 at 11 51 25" src="https://user-images.githubusercontent.com/19720404/113600172-3d288280-9605-11eb-8026-c41369590af2.png">

Reproduction repository:

https://github.com/rockchalkwushock/codybrunner.dev/pull/84

Problem description:

It seems as though if running either `webpack@4` or opting in for `webpack@5` in `next` there is an issue with the resolving of `esm` imports.

**Comment by rockchalkwushock** [comment]
@kentcdodds I spent a few hours this morning trying to figure this out further but to no avail. I actually get an entirely new error message 🤦🏻‍♂️ 

I opened a new repository [here](https://github.com/rockchalkwushock/mdx-bundler-bug-reproduction) that would remove the other dependencies from my website repository as possible culprits and opted to just look at the last version of `next` that still runs on `webpack@4.x`.

`next@10.0.9`
`mdx-bundler@3.1.2`
`node@14.15.4`
`yarn@1.22.10`

I cleared out caches, removed `node_modules`, removed `.next`, but regardless of what I tried to get back to the above error I would end up with the following:

## `yarn dev`

<img width="2557" alt="Screen Shot 2021-04-06 at 10 30 35" src="https://user-images.githubusercontent.com/19720404/113738202-517f8480-96c4-11eb-80a8-2e8b3c716286.png">

## `yarn build`

<img width="1662" alt="Screen Shot 2021-04-06 at 10 31 27" src="https://user-images.githubusercontent.com/19720404/113738243-5ba18300-96c4-11eb-8299-8ad754bc7a19.png">

**Comment by kentcdodds** [comment]
Try `npm update`: https://github.com/wooorm/xdm/pull/35#issuecomment-815897821

**Comment by rockchalkwushock** [comment]
@kentcdodds followed your comment from above in the repository I made for reproducing this bug and it solved the `astring` problem I ran into while trying to reproduce the core issue here.  That got me up and running and I have been completely unable to reproduce the initial problem in this issue. I can successfully get `mdx-bundler` working with:

```txt
next@10.0.9 // running webpack 4
next@10.1.3 // running webpack 4
next@10.1.3 // opting-in for webpack 5
```

Not really sure what caused this 🤷🏻‍♂️ 

Thanks for your prompt help with this matter, very cool library you have made here! 🎉 

Closing

**Comment by kentcdodds** [comment]
Glad it's working!

**Comment by IanMitchell** [comment]
@rockchalkwushock any idea what may have solved the initial error, or even what caused it? I'm running into the error as well and I'm not having much luck getting past it (for clarity, the `builtin-modules` error)

**Comment by Arcath** [comment]
> EDIT: It almost seems as like using bundleMDX outside of a Next.js page breaks things, but if I move it inside of `getStaticProps` it looks like it runs successfully

When you say outside `getStaticProps` what do you mean?

I call `bundleMDX` inside my `prepareMDX` function which is called directly from `getStaticProps` and nowhere else. https://github.com/Arcath/arcath.net-next/blob/main/lib/functions/prepare-mdx.ts#L12

If you are bundling your MDX for every page/post every time you build data I could see that cauing issues with esbuild's service.

**Comment by rockchalkwushock** [comment]
@IanMitchell sorry just now seeing this.

I do believe I figured out what the problem is surrounding that error message. In my project all third-party service code lives in `lib/` and those files are export from the `index.ts` like so:

```ts
export * from './service'
```

The service's code is then imported as:

```ts
import { getMDXFiles, prepareMDX } from '@lib'
```

So the `mdx` service was exported like that and whenever I added another service and exported it in the same manner this error message would arise: `Module not found: Can't resolve 'builtin-modules'`

```ts
// No bueno
export * from './mdx'
export * from './spotify'
```

To fix this I simply removed the `export * from './mdx'` and changed the import for that service to be:

```ts
import { getMDXFIles, prepareMDX } from '../lib/mdx'
```

I ran into a similar issue when using `firebase-admin` and stumbled upon a note I left myself months ago about....at least why this was an issue with `firebase-admin`:

```ts
// pages/api/views/[...slug].ts

// You cannot use the @lib alias here and export * from './firebase' from the lib directory.
// The reason being that 'firebase-admin' is then being made available in the
// client-side code and this is a node based package. Shit gets hairy fast!
// This took like 30 minutes to figure out what was going wrong 🤦🏻‍♂️
import { getPostViews, updatePostViews } from '../../../lib/firebase'

...
```

For further reference it seems as though this is a `webpack` [bug](https://github.com/webpack/webpack/issues/11376) that was solved some time ago (not sure what release it was packaged in). `next` is using `webpack@4.44.1`  I am yet to figure out which version of `webpack@5` is being used but you can see [here](https://github.com/vercel/next.js/blob/canary/packages/next/next-server/server/config-utils.ts#L123) were they switch the loading if you opt-in.

My assumption is that not `mdx-bundler` but `xdm || esbuild (the more likely culprit)` has some internal code that is clashing with the other modules when exporting and `webpack` no likey. My understanding of the ESM import/exports is not the greatest, although I did see @kentcdodds released a post recently on this that I need to take the time to read.

Hope this helps you out 🎉 🥂

**Comment by rockchalkwushock** [comment]
@IanMitchell another solution (although I would not recommend it) is to do the following in your `next.config.js`

```js
module.exports = {
  future: {
    // Opt-in to webpack@5
    webpack5: true,
  },
  reactStrictMode: true,
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    if (!isServer) {
      // https://github.com/vercel/next.js/issues/7755
      config.resolve = {
        ...config.resolve,
        fallback: {
          ...config.resolve.fallback,
          child_process: false,
          fs: false,
          'builtin-modules': false,
          worker_threads: false,
        },
      }
    }

    return config
  },
}
```

After a lot of reading this afternoon the underlying problem is that **somewhere** we are _accidentally_ shipping node based code in the client bundle. I found the following [resource](https://next-code-elimination.vercel.app/) from Vercel for seeing what is bundled for the client. I haven't begun using it yet to try and debug where I am accidentally shipping those node packages yet.

**Comment by IanMitchell** [comment]
Thanks everyone for the help! Managed to get it working 🙏 really appreciate the replies!

**Comment by nebrelbug** [comment]
For anyone else who stumbles upon this issue, my problem ended up being that I was importing from `mdx-bundler` instead of `mdx-bundler/client`.

**Comment by Tylerrutt17** [comment]
@nebrelbug lifesaver
