### ISSUE TITLE
mdx-bundler should support Next.js 13 data fetching strategies via `use()` hook

### ISSUE THREAD

**Issue by NateRadebaugh** [kentcdodds/mdx-bundler#192]
- `mdx-bundler` version: `9.0.1`
- `node` version: `v16.18.0`
- `npm` version:: `8.19.2`
- `next` version: `13.0.0`

Relevant code or config

```js

```

What you did:

Updated my nextjs app to use Next.js 13. Replaced `getStaticProps` with `use(getData())`

What happened:

<img width="920" alt="image" src="https://user-images.githubusercontent.com/130445/197907786-631a18a6-c9b8-4556-81ec-918481ae9d32.png">

**Comment by mattboon** [comment]
Think this can be fixed with `serverComponentsExternalPackages` in `next.config` [Link to docs](https://beta.nextjs.org/docs/api-reference/next.config.js#servercomponentsexternalpackages)

```js
experimental: {
  serverComponentsExternalPackages: ["mdx-bundler"],
}
```

Full code:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
    serverComponentsExternalPackages: ["mdx-bundler"],
  },
};

module.exports = nextConfig;
```

**Comment by NateRadebaugh** [comment]
Thanks, that worked!
