### ISSUE TITLE
Question: Using remark/rehype plugins on a per-page basis?

### ISSUE THREAD

**Issue by colinsteidtmann** [kentcdodds/mdx-bundler#197]
Hi, I want to use a rehype plugin, [rehype-external-links](https://github.com/rehypejs/rehype-external-links), for a few specific mdx files. Is it possible to do this without creating separate ``bundleMDX({...})`` functions?

**Comment by Owen-Tsai** [comment]
Is it possible in your use case to create different options and pass them to the `bundleMDX` method? In the ideal situation you'll just need to slightly modify your existing code.

**Comment by colinsteidtmann** [comment]
Yes, it's totally possible. I wrote this post before I understood mdx-bundler. Since you're bundling mdx files on a per-file basis, then you can easily have a general function that bundles an mdx file with generic plugins, but allow it to accept an array of additional plugins that you may want for specific files.
