### ISSUE TITLE
Support for mdx v3?

### ISSUE THREAD

**Issue by tonyxiao** [kentcdodds/mdx-bundler#220]
The main readme says this uses mdx v2, but v3 has been released. Are there plans to support that?

**Comment by verdverm** [comment]
The 2 big items (there's not much more)
1. support for `await`
2. ES2024

https://mdxjs.com/blog/v3/

**Comment by verdverm** [comment]
Actually, is this just an outdated readme?

https://github.com/kentcdodds/mdx-bundler/commit/da24af7aaa186244a7a9993258a71338e8c420de

**Comment by verdverm** [comment]
It is, just tested that `{ await Promise.resolve(42)}` works!

**Comment by verdverm** [comment]
I would update the README first
