### ISSUE TITLE
`files` vs virutal `path`?

### ISSUE THREAD

**Issue by mikestopcontinues** [kentcdodds/mdx-bundler#28]
I'm considering using `mdx-bundler`, and I ran into a snag reading the docs. The `files` option seems really weird to me. I understand the library is designed so that the mdx content doesn't need to exist on the filesystem, but part of what's so nice about mdx is that it behaves as if it does.

Do I understand correctly that an import like `import Button from './components/Button'` won't work out of the box? And that a user has to specify up front every import any content might use, import them, and build the `files` object—relative to the particular mdx file being loaded?

Assuming so, is it possible to circumvent this complexity by specifying a virtual `path` for the mdx content? If the doc at least _seems_ to live on the filesystem, `esbuild` should be able to handle the rest, including alias, tsconfig paths, etc. Naturally if the mdx lives on the filesystem, you could just pass its actual path. 

Am I missing something about the problem? Is this feasible? Thanks!

**Comment by kentcdodds** [comment]
Hi @mikestopcontinues,

That's not the original intent of this project, but I'm willing to entertain a PR to support what you're talking about if anyone's willing to open one up. If it doesn't add a lot of complexity to the API or the implementation then I'll probably accept it.

**Comment by Arcath** [comment]
I've opened a PR #29 that should solve this.

You could pass the folder you read the MDX from and get an experiance like Gatsby where you can just import anything relative to your mdx file.

Other option is you can pass a _fake_ path that is the location you'd like to pretend all externally loaded MDX is run from.

**Comment by mikestopcontinues** [comment]
@Arcath You rock. I just sat down to figure this out. Thanks!
