### ISSUE TITLE
Expose matter function (from gray-matter) through mdx-bundler

### ISSUE THREAD

**Issue by adrserr** [kentcdodds/mdx-bundler#32]
- `mdx-bundler` version: 3.2.1
- `node` version: 14.13.1
- `npm` version: 6.14.8

Relevant code or config

```js
import { matter } from 'mdx-bundler'
import readingTime from 'reading-time'

......
export const getStaticProps = async () => {
  const source = getPost('./data/blog/thePost');

  const { content, data } = matter(source);

  return {
    props: {
      ...data,
      readingTime: readingTime(content)   
    }
  }
}
```

What you did:
I'm creating a blog with next.js using mdx-bundler to get mdx code and frontmatter.

What happened:
I get always code and frontmatter from bundleMDX function

Problem description:
Sometimes only frontmatter is needed, for example, when rendering a list of post but not the post itself( where you don't really need the code). Another case might be when trying to display the reading time, where you need plain content to be more accurate instead of the string with generated code.

Suggested solution:
Exposing matter function (from gray-matter library) through mdx-bundler, so there is no need to add it to project dependencies.

Another option is having the possibility of only getting plain content and frontmatter from bundleMDX, instead of always getting the code.

Thanks to everyone, this is an awesome library!

**Comment by kentcdodds** [comment]
Hi @adrserr,

Personally I don't want to just re-export `gray-matter` from this library. That would mean that breaking changes in `gray-matter` are breaking changes for us which I don't think is wise.

Thanks anyway!
