### ISSUE TITLE
It says it needs Python to install

### ISSUE THREAD

**Issue by itartpro** [kentcdodds/mdx-bundler#35]
Hello, it says it needs Python....but no mention of python needed in the docs...
My environment is node:alpine docker container

/app/front # npm i --save mdx-bundler
npm WARN deprecated @types/source-map@0.5.7: This is a stub types definition for source-map (https://github.com/mozilla/source-map). source-map provides its own type definitions, so you don't need @types/source-map installed!
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /app/front/node_modules/deasync
npm ERR! command failed
npm ERR! command sh -c node ./build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.0.0 | linux | x64
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python2" can be used
npm ERR! gyp ERR! find Python - "python2" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.

**Comment by Arcath** [comment]
Looks like [deasync](https://www.npmjs.com/package/deasync) needs python installed to build itself. deasync is a dependancy of [xdm](https://github.com/wooorm/xdm) which is a core dependancy of `mdx-bundler`.

I'll add a note to the Readme that [node-gyp](https://github.com/nodejs/node-gyp#installation) needs to be setup on the machine.

**Comment by kentcdodds** [comment]
I don't think we even use the code that requires deasync. I wonder whether there can be a change in xdm to avoid requiring that dependency. cc @wooorm

**Comment by wooorm** [comment]
If I make it an `optionalDependencies`, that should solve solve this error, right? 🤔

**Comment by kentcdodds** [comment]
I don't know 😅 I've never used those before either

**Comment by wooorm** [comment]
Tried the `optionalDependencies` route — hope that works!

**Comment by kentcdodds** [comment]
Thanks! Hopefully nobody else complains about it 😅
