### ISSUE TITLE
Importing mdx files from node_modules doesn't work

### ISSUE THREAD

**Issue by gaelhameon** [kentcdodds/mdx-bundler#41]
Hi ! Thanks for this neat tool !

I'd like to use it to do some transclusion of Mdx files, some of which I would like to manage as individual npm packages.

My understanding of the comment below is that this should work out of the box: 
https://github.com/kentcdodds/mdx-bundler/blob/2802158695c86fa6e8cc271bb1fb62466bdf22ee/src/index.js#L150-L157

But I can't make it work ...

I've created a new test case in [my fork](https://github.com/gaelhameon/mdx-bundler/blob/e988804b16592e98586e6def3d51bd2dd50cacc6/src/__tests__/index.js#L115) to illustrate:

```javascript
test('bundles mdx files from node_modules', async () => {
  const mdxSource = `
import MdxTestData from 'mdx-test-data'
The content below was imported from an MDX File in node_modules.
<MdxTestData />
  `.trim()

  const result = await bundleMDX(mdxSource, {
    files: {},
  })

  const Component = getMDXComponent(result.code)
  render(React.createElement(Component))
})
```

`mdx-test-data` is [a package](https://www.npmjs.com/package/mdx-test-data) that simply exposes `README.mdx` in the  `main` field of `package.json`

And running this test yields this result: 

```
   FAIL  "bundles mdx files from node_modules"
    Build failed with 1 error:
__mdx_bundler_fake_dir__/_mdx_bundler_entry_point.mdx:2:24: error: No loader is configured for ".mdx" files: node_modules/mdx-test-data/README.mdx

    __mdx_bundler_fake_dir__/_mdx_bundler_entry_point.mdx:2:24: error: No loader is configured for ".mdx" files: node_modules/mdx-test-data/README.mdx
    at failureErrorWithLog (C:/Users/gaelh/dev/mdx-bundler/node_modules/esbuild/lib/main.js:1432:15)
    at C:/Users/gaelh/dev/mdx-bundler/node_modules/esbuild/lib/main.js:1114:28
    at runOnEndCallbacks (C:/Users/gaelh/dev/mdx-bundler/node_modules/esbuild/lib/main.js:912:47)
    at buildResponseToResult (C:/Users/gaelh/dev/mdx-bundler/node_modules/esbuild/lib/main.js:1112:7)
    at C:/Users/gaelh/dev/mdx-bundler/node_modules/esbuild/lib/main.js:1219:14
    at C:/Users/gaelh/dev/mdx-bundler/node_modules/esbuild/lib/main.js:603:9
    at handleIncomingPacket (C:/Users/gaelh/dev/mdx-bundler/node_modules/esbuild/lib/main.js:700:9)
    at Socket.readFromStdout (C:/Users/gaelh/dev/mdx-bundler/node_modules/esbuild/lib/main.js:570:7)
    at Socket.emit (events.js:315:20)
```

Am I missing something ? Is there another way of importing mdx files from node_modules ?

**Comment by kentcdodds** [comment]
I expected this would work but I'm not entirely surprised it doesn't because I never tested it. Not sure how to fix it though

**Comment by gaelhameon** [comment]
I think I may have a lead that I will keep exploring tomorrow.
I inverted the registration order of the `inMemoryPlugin` and the `xdmESBuild` plugin.
If I just do that, it fails, which is totally logical: 
```
 > error: [plugin: esbuild-xdm] ENOENT: no such file or directory, open 'C:\Users\gaelh\dev\mdx-bundler\__mdx_bundler_fake_dir__\_mdx_bundler_entry_point.mdx'
``` 
But if I add the config below to the xdm plugin (and change the extension of my mdx file in node_modules to .mdx2), it seems to work:
```javascript
      xdmESBuild({
        format: 'mdx',
        mdxExtensions: ['.mdx2']
      }),
      inMemoryPlugin,
```

In other words, when the inMemoryPlugin is registered before the xdm plugin, the build fails as soon as a node_modules mdx file is encountered in one of the in-memory files, because esbuild doesn't know yet that the xdm plugin is available and can be used to load mdx files.

If the xdm plugin is registered before, it seems to work. But then the problem is to find a better way to tell the xdm plugin to leave the in-memory files to the inMemoryPlugin, because the .mdx2 extension is not very nice ...

**Comment by gaelhameon** [comment]
When I return `null` instead of `{}` in the lines below, everything seems to work !

https://github.com/kentcdodds/mdx-bundler/blob/4664b61e8e6117689563e9bfbfaea8c6310f8a3e/src/index.js#L73-L74

https://github.com/kentcdodds/mdx-bundler/blob/4664b61e8e6117689563e9bfbfaea8c6310f8a3e/src/index.js#L79-L80

**Comment by gaelhameon** [comment]
The [esbuild doc](https://esbuild.github.io/plugins/#resolve-results) is not very clear to me ...

> This is the object that can be returned by a callback added using onResolve to provide a custom path resolution. If you would like to return from the callback without providing a path, just return the default value (**so undefined in JavaScript** and OnResolveResult{} in Go). Here are the optional properties that can be returned:

This suggests setting the whole return value as undefined

But then: 

> path
> Set this to a non-empty string to resolve the import to a specific path. If this is set, no more on-resolve callbacks will be run for this import path in this module. If this is not set, esbuild will continue to run on-resolve callbacks that were registered after the current one. Then, if the path still isn't resolved, esbuild will default to resolving the path relative to the resolve directory of the current module.

According to this, returning empty object should work as well ...

I'll create a PR to return undefined

**Comment by Arcath** [comment]
@gaelhameon returning an empty object should work as I interpret the docs.

I have seen some behaviour in esbuild where if a plugin returns anything it gets first dibs on the next phase, but that should still have passed over to `xdmEsbuild` when the `inMemory` onLoad callback returned `{}`

Bit strange.

**Comment by gaelhameon** [comment]
@Arcath yeah it is strange
I used the "debug" plugin below to figure out what was going on while working on this issue.
I was thinking of cleaning it up and maybe using it in a new test in the esbuild repo, and eventually suggesting improvements to the docs ... But in a first quick look at the repo, I couldn't find the tests or the docs ...

```javascript
  /** @returns {import('esbuild').Plugin} */
  const debugPlugin = (subName) => {
    const name = `debug-${subName}`;
    return {
      name,
      setup(build) {
        build.onResolve({ filter: /.*/ }, ({ path: filePath, importer }) => {
          console.log(`Top of ${name} onResolve`)
          console.log({ filePath })
          console.log({ importer })
          return null;
        })

        build.onLoad({ filter: /.*/ }, async ({ path: filePath, pluginData }) => {
          console.log(`Top of ${name} onLoad`)
          console.log({ filePath })
          console.log({ pluginData })
          return {}
        })
      },
    }
  }
```

**Comment by Arcath** [comment]
Can you confirm that 4.0.0 has fixed this for you?

**Comment by gaelhameon** [comment]
@Arcath , yes, 4.0.0 has fixed this for me. Thanks !
