### ISSUE TITLE
Add debugging output to the inMemory plugin

### ISSUE THREAD

**Issue by gaelhameon** [kentcdodds/mdx-bundler#47]
While working on #41 , I added `console.log` in a couple of places to better understand what was going on.
You can have a look here: https://github.com/kentcdodds/mdx-bundler/compare/main...gaelhameon:wip

What would you think of including  [debug ](https://www.npmjs.com/package/debug) as a dependency, and turning these `console.log` into actual debugging output ?

I'm guessing that it could prove useful for cases where we load files that load other files that load other files etc.

@kentcdodds , if I submitted a PR for that, is this something you'd be interested in merging ?

**Comment by kentcdodds** [comment]
Personally by the time I realize that I can use `debug` on a package, I've already started digging into the source code and I can manually insert my own log statements, so I'm not sure I feel like it's necessary 🤷
