### ISSUE TITLE
error when using styled-components in imported components

### ISSUE THREAD

**Issue by souporserious** [kentcdodds/mdx-bundler#48]
- `mdx-bundler` version: 3.4.1
- `node` version: 14.16.1
- `npm` version: 6.14.12

#### What you did:

Import a component that uses `styled-cmponents`:

```tsx
import { Counter } from './components/Counter';

# Counter Example

<Counter />
```

```tsx
import * as React from 'react';
import styled from 'styled-components';

const StyledContainer = styled.div`
  display: flex;
  background-color: orange;
`;

export function Counter() {
  const [count, setCount] = React.useState(0);
  return (
    <StyledContainer>
      {count} <button onClick={() => setCount(count + 1)}>Increment</button>
    </StyledContainer>
  );
}
```

#### What happened:

Errors seemingly about `styled-components`, other third-party libraries all seem to work fine:

![image](https://user-images.githubusercontent.com/2762082/117516469-0a4c1400-af4e-11eb-842d-5fcc5909344a.png)

#### Reproduction repository:

https://github.com/souporserious/mdx-bundler-and-styled-components

#### Problem description:

This is in the context of a NextJS app that reaches into another directory outside of the app and pulls all of the MDX files from it. This works without `styled-components`, but when it's added, I get the error above.

This is my `getStaticProps` function responsible for fetching the MDX files:

```ts
export const getStaticProps: GetStaticProps = async ({ params }) => {
  const filePaths = await glob([
    path.resolve(__dirname, '../../../../../vapor/src/**/*.mdx'),
  ]);
  const filePath = filePaths.find((filePath) => {
    const extension = path.extname(filePath);
    const name = path
      .basename(filePath, extension)
      .split('.stories')[0];
    return name.toLowerCase().replace(/\s/g, '-') === params.slug;
  });
  const contents = await fs.readFile(path.resolve(filePath), 'utf-8');
  const { code, frontmatter } = await bundleMDX(contents, {
    cwd: path.dirname(filePath),
  });
  return {
    props: {
      code,
      frontmatter,
    },
  };
};
```

**Comment by Arcath** [comment]
Looks like `esbuild` needs to be told to build for Node.

You can set the platform using the `esbuildOptions` parameter in `bundleMdx` like so:

```ts
const { code, frontmatter } = await bundleMDX(contents, {
  cwd: path.dirname(filePath),
  esbuildOptions: (options) => {
    options.platform = 'node'

    return options
  }
})
```

This got it working on your demo repository for me.

**Comment by souporserious** [comment]
@Arcath that was it! 🎉 Thank you so much for looking into this, I appreciate your help!
