### ISSUE TITLE
Does not work on Vercel inside getServerSideProps from Next.js

### ISSUE THREAD

**Issue by Divlo** [kentcdodds/mdx-bundler#50]
Thanks for making this awesome `npm` package! :smile: 

- `mdx-bundler` version: 4.0.0
- `node` version: 14.16.1
- `npm` version: 7.12.1

Problem description:

The `bundleMDX` function seems to doesn't work in Vercel when it is in `getServerSideProps` function from Next.js, but it actually works if it is in `getStaticProps`.
Also both work in local, I don't have errors at all on my local machine.
You can see see that currently it is a 500 error page : https://divlo-nlxbiy7k2-divlo.vercel.app/blog/hello-world
I saw that there was similar closed issue : #2 

You can see the relevant code there : https://github.com/Divlo/Divlo/blob/feat/add-blog/pages/blog/%5Bslug%5D.tsx

Here is the log from the serverless function in Vercel : 

```
ERROR	Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/periscopic/node_modules/estree-walker/dist/esm/estree-walker.js' imported from /var/task/node_modules/periscopic/src/index.js
Did you mean to import estree-walker/dist/umd/estree-walker.js?
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Thanks for your help!

**Comment by kentcdodds** [comment]
@joelhooks hit this today as well. Coming from xdm. Cc @wooorm

**Comment by wooorm** [comment]
I think it’s this: https://github.com/Rich-Harris/periscopic/issues/10

**Comment by wooorm** [comment]
`yarn` has resolutions, maybe you could use that to force estree-walker@3 and see if that works.

I don’t use Next and I don’t if they’re doing any “post processing” on `getServerSideProps`

**Comment by wooorm** [comment]
You might also just run into Next not liking ESM. And then this might help: https://github.com/wooorm/xdm/issues/32#issuecomment-808750922

**Comment by Divlo** [comment]
> `yarn` has resolutions, maybe you could use that to force estree-walker@3 and see if that works.
> 
> I don’t use Next and I don’t if they’re doing any “post processing” on `getServerSideProps`

I did it with `npm` but the result is the same, Indeed it fixes the issue, thanks for your help!
But yes forcing the installation of an npm package by editing manually `package-lock.json`, it is not great.

So the issue will be definitely be fix once this issue will be closed : https://github.com/Rich-Harris/periscopic/issues/10

**Comment by wooorm** [comment]
are you on webpack 5? That might do something. I think Next is updating to that but it’s not completely the default yet?

**Comment by Divlo** [comment]
I'm using webpack 4, since I edited the `next.config.js` (for translations and PWA stuff) it is not taken by default, if you don't have `next.config.js`, yes webpack 5 is the default.

I don't think it is part of the problem, since it's working on my local machine anyway, I don't really know what's going on the Vercel side.

**Comment by wooorm** [comment]
Could you check? I think it’s quite likely given that a) Webpack 4 is bad at ESM, b) this is an ESM related project, c) Next heavily uses Webpack 4, d) non-Next folks don’t run into this problem

**Comment by Divlo** [comment]
I reverted the fix with `package-lock.json` and added this to my `next.config.js` so it could use Webpack 5 :
```js
future: {
  webpack5: true
}
```

It doesn't solve the issue, as you can see there is a 500 error page : https://divlo-1b94t73i7-divlo.vercel.app/blog/hello-world
Currently the workaround to make it work, is to manually edit `package-lock.json`, and update `estree-walker@3` for the `periscopic` part, by doing that it works.

> For the only-in-production part, I am assuming that Next/Vercel is doing some extra optimization only in that case

Yes probably, that makes sense.

**Comment by wooorm** [comment]
I can’t see the 500 error logs, is that still the same one as before?

---

Hmm, okay, unfortunate. Thanks for checking!

**Comment by wooorm** [comment]
Patch is released!

**Comment by Divlo** [comment]
We can close this issue! Things work properly on the Vercel platform!
