### ISSUE TITLE
Origin of vfile message when using remark plugin

### ISSUE THREAD

**Issue by aphecetche** [kentcdodds/mdx-bundler#51]
I'm using a custom remarkPlugin that adds some message to a vfile under certain condition (broken link) : 

```
const mdxFile = (route: string) => {
  // returns true or false depending on whether route is valid or not
  ...
}

const attacher = () => {
  return transformer

  function transformer(tree, file) {
    visit(tree, { type: "link" }, (node: Node) => {
      const lnode = node as LinkNode
      const route: string = lnode.url
      if (!/^http/.test(route) && !mdxFile(route)) {
        file.message(`${route} is not a valid link`)
        const title = lnode.title || ""
        lnode.title = `[BROKEN LINK]${title}`
      }
    })
  }
}
```

I'm later on using it like so : 
  
```
const rawContent = fs.readFileSync(filePath).toString()
  const { code, frontmatter } = await bundleMDX(rawContent, {
    xdmOptions(options) {
      options.remarkPlugins = [...(options.remarkPlugins ?? []), brokenLinks]
      return options
    },
  })
```

It's kinda working but the output is not as helpful as I'd like as I'm loosing track of the original filePath  : 

```
> __mdx_bundler_fake_dir__/_mdx_bundler_entry_point.mdx:0:0: warning: [plugin: esbuild-xdm] /fr/recherche/equipes/sen/collisions-d-ions-lourds-et-equation-d-etat-de-la-matiere-nucleaire-2 is not a valid link
    0 │ ---
      ╵ ^
```

Is there a way to get the part before the warning (`__mdx_bundler_fake_dir__/_mdx_bundler_entry_point.mdx:0:0` be the `filePath` ?

Using the `cwd` `bundleMDX` param I was able to change the `__mdx_bundler_fake_dir__` part, but have no clue on how to deal with the other part (`_mdx_bundler_entry_point.mdx:0:0`).

Sorry if that's obvious.

- `mdx-bundler` version: 4.0.0
- `node` version: 14.15.3
- `npm` version: 6.14.9

**Comment by Arcath** [comment]
`_mdx_bundler_entry_point.mdx` is the _fake_ file we create in memory to hold the mdx source passed as the first option to `bundleMDX`.

You could replace the entry point in esbuild with the file on disk and it should give you the real path in errors.

```js
const { code, frontmatter } = await bundleMDX('', {
  esbuildOptions(options) {
    options.entryPoints = [filePath]
    return options
  },
  xdmOptions(options) {
    options.remarkPlugins = [...(options.remarkPlugins ?? []), brokenLinks]
    return options
  },
})
```

This would then ignore the now empty in memory entry point and read your file straight from disk. Added bonus, you wont have to read the file contents in yourself either as esbuild will do it for you.

**Comment by Arcath** [comment]
@aphecetche 4.1.0 has tests for this now and supports [replacing the entry point](https://github.com/kentcdodds/mdx-bundler#replacing-the-entry-point) properly now.

**Comment by aphecetche** [comment]
@Arcath thanks a lot. Have been diverted from this for a while, will test as soon as I can.

**Comment by aphecetche** [comment]
Actually works perfectly. Thanks !
