### ISSUE TITLE
Unable to Add remark plugins

### ISSUE THREAD

**Issue by JanaSundar** [kentcdodds/mdx-bundler#65]
Hi there,

 I Stored my data on Graphcms. Mdx bundling is working fine, but I'm unable to add a remark plugin to the bundler. I tried to add this plugin separately **remark-admonitions** and **remark-mdx-code-meta**, but I'm getting this same error. Can you tell me how to resolve this?

<img width="1286" alt="Screenshot 2021-07-15 at 6 03 07 PM" src="https://user-images.githubusercontent.com/30264201/125790123-17abb272-565e-4613-9a76-0aa6d2b6fe42.png">

**Comment by Arcath** [comment]
Could you post the code your using for `bundleMDX`?

**Comment by JanaSundar** [comment]
<img width="1156" alt="Screenshot 2021-07-15 at 6 49 10 PM" src="https://user-images.githubusercontent.com/30264201/125794738-782129bc-f2c0-467c-9159-47074e2a6fce.png">

**Comment by JanaSundar** [comment]
@Arcath  I'm rendering like this in the mdx bundler

<img width="1156" alt="Screenshot 2021-07-15 at 9 30 39 PM" src="https://user-images.githubusercontent.com/30264201/125820970-4ea174ff-da9b-43c2-9391-db6d97bc4ebc.png">

**Comment by JanaSundar** [comment]
@Arcath could you please tell me how to fix this issue

**Comment by Arcath** [comment]
Not sure what is going on here. It's coming from inside the XDM plugin which makes me wonder if one of those plugins can't handle XDM.

Can you try with just the rehype plugins and then just the remark plugins to see if the error is bound to one of them.

**Comment by souporserious** [comment]
Running into this same error. It happens when I try to modify `node.type` to be `html` in my case for the shiki syntax highlighter.
