### ISSUE TITLE
Gray-matter options?

### ISSUE THREAD

**Issue by jpaas** [kentcdodds/mdx-bundler#72]
- `mdx-bundler` version: 5.1.2
- `node` version: 14.17.3
- `npm` version: 6.14.13

Relevant code or config

```mdx
---
title: Test Post
published: 2021-02-13
description: Shows how a post is published via MDX
---

# Test Post

This is a test post
```

What you did:
I'm using mdx-bundler to build a nextjs static site. My frontmatter contains some date-looking things. I pass the frontmatter returned by `bundleMDX` as props for my component.

What happened:
Since its a static site, Nextjs tries to serialize the props as part of the component and fails because it isn't JSON serializable:
```
Error: Error serializing `.frontmatter.published` returned from `getStaticProps` in "/posts/[slug]".
Reason: `object` ("[object Date]") cannot be serialized as JSON. Please only return JSON serializable data types.
```
Problem description:
There's no way to configure the default gray-matter engine behavior.

Suggested solution:
I guess the most obvious thing is to provide the ability to pass options to gray-matter.

**Comment by jpaas** [comment]
I have a decent workaround. If I enclose the value in quotes, it is treated as a string and I deal with date parsing at runtime in my React component...
```
---
title: This the Test Post Title
published: "2021-02-13"
description: Shows how a post is published via MDX
---

# {frontmatter.title}

This is a test post

Published {frontmatter.published}
```

So not  a burning issue I suppose. But still might be important for someone else.

**Comment by Arcath** [comment]
I've opened a PR to allow access to the gray matter options.

**Comment by Arcath** [comment]
This has been released in 5.2.0!

**Comment by jpaas** [comment]
Thanks so much @Arcath !

**Comment by barrymay** [comment]
FYI - since I ran into the same issue and am a little new to gray-matter/MDX processing, after jumping thru the google-sphere to get answers I felt dropping an example usage of graymatterOptions that solves the original question would be helpful to others:

This returns **published** as a string, not a date, which is typical for most JSON-parsed results anyway.

```ts
import yaml from "js-yaml";

// ---- 
  await bundleMDX(source, {
    grayMatterOptions: (options) => {
      // set other gray-matter options, like excerpt
      options.engines = {
        yaml: (s) => yaml.load(s, { schema: yaml.JSON_SCHEMA }) as object,
      };
      return options;
    },
  } 
// ---- 
```

If you're using `matter` elsewhere, use the same thing (hence the whole point of grayMatterOptions):
```ts
import yaml from "js-yaml";

// ---- 
      const { data } = matter(source, {
        engines: {
          yaml: (s) => yaml.load(s, { schema: yaml.JSON_SCHEMA }) as object,
        },
      });
// --- 
```

Thanks to @Arcath and @jpaas for the solution and original question :)

**Comment by josephbales** [comment]
@barrymay You are a legend. Thanks for this tidbit!  Got me going again!
