### ISSUE TITLE
Can't read markdown paragraph including "<" and ">" with mdx-bundler.

### ISSUE THREAD

**Issue by j3ygithub** [kentcdodds/mdx-bundler#82]
I can't read markdown paragraph including "<" and ">" with mdx-bundler.

like:

```
...
The <h1> is for heading, <p> is for paragraph.
... 
```

I can do this with [mdx](https://github.com/mdx-js/mdx) though.
Is it anything need to add in text, when using `mdx-bundler`?

**Comment by Arcath** [comment]
Looks like `xdm` handles these differently.

Personally I would always put example HTML (or any code) in backticks so that it gets put in a `<code>` or `<pre>` tag.

```
The `<h1>` is for heading, `<p>` is for paragraph.
```

Previewed this reply and Github isn't happy with it either, and it formats weirdly like so

The <h1> is for heading, <p> is for paragraph.

**Comment by j3ygithub** [comment]
Thank you for replying that soon, I really appreciate that.
If I want to make sure all my mdx string will be converted to what it would be done on Github.
Is this the way?
```
import gfm from "remark-gfm";

const something = await bundleMDX(source, {
  cwd: POSTS_PATH,
  xdmOptions: (options) => {
    options.remarkPlugins = [
      ...(options.remarkPlugins ?? []),
      //remarkHighlight,
      gfm
    ];
    return options;
  }
)
```

I saw it [here](https://github.com/Arcath/arcath.net-next/blob/main/lib/functions/prepare-mdx.ts?#L39).

**Comment by Arcath** [comment]
Yeah thats what I do. [remark-gfm](https://github.com/remarkjs/remark-gfm) adds all the github features and works no problem for me.
