### ISSUE TITLE
Thanks for the quick fix!

### ISSUE THREAD

**Issue by rockchalkwushock** [kentcdodds/mdx-bundler#86]
I was literally just racking my brain about this ESM bug with `remark-frontmatter` and was writing an issue for it when you fixed it in https://github.com/kentcdodds/mdx-bundler/commit/f6bebc9e4763a91d5ec042ed669c5c726f455d7a. Working great now! 🎉 

Thanks @kentcdodds

**Comment by kentcdodds** [comment]
Yeah, sorry about that 😅 And you're welcome!
