### ISSUE TITLE
Question about bundleMDX (files, globals, cwd)

### ISSUE THREAD

**Issue by chrislicodes** [kentcdodds/mdx-bundler#87]
Hi, 

thanks for building this project!

- `mdx-bundler` version: ^5.2.1
- `node` version: 15.14.0
- `npm` version: 7.15.0

I am currently working on building this blog: https://github.com/chrislicodes/personal-blog.

The function to bundle the MDX looks like this:

```js
export const prepareMDX = async (directoryName: string) => {
  if (process.platform === "win32") {
    process.env.ESBUILD_BINARY_PATH = path.join(
      process.cwd(),
      "node_modules",
      "esbuild",
      "esbuild.exe"
    );
  } else {
    process.env.ESBUILD_BINARY_PATH = path.join(
      process.cwd(),
      "node_modules",
      "esbuild",
      "bin",
      "esbuild"
    );
  }

  const directory = path.join(POSTS_PATH, "/", directoryName);

  const source = getSourceOfFile(directory + "/index.mdx");

  // const files = await getComponents(directoryName);

  const { code, frontmatter } = await bundleMDX(source, {
    // files,
    cwd: directory,
    xdmOptions: (options) => {
      options.remarkPlugins = [
        ...(options.remarkPlugins ?? []),
        remarkMdxImages,
      ];

      return options;
    },
    esbuildOptions: (options) => {
      options.outdir = path.join(process.cwd(), "/public/img");
      options.loader = {
        ...options.loader,
        ".png": "file",
        ".jpg": "file",
        ".gif": "file",
        ".mp3": "file",
      };
      options.publicPath = "/img/";
      options.write = true;

      return options;
    },
  });

  return { frontmatter, code };
};

```

In this post, I am importing a component using React Three Fiber: 

https://github.com/chrislicodes/personal-blog/blob/main/src/_posts/three-js-post/index.mdx

Using it this way leads to multiple instances of THREE being imported. The multiple imports should be fixed using the "globals" parameter, or would that only apply I import the libraries in the .mdx file directly?

My questions:

1) With passing the "cwd" parameter, the imports in a .mdx file can be resolved - in which scenarios would I have to pass/use the "files" parameter? 
2) Can I fix the multiple THREE.js instances with the "globals" parameter, or would that only be needed if I import a library directly in an MDX file?

**Comment by Arcath** [comment]
`files` is a precursor to `cwd`. Originally you had to specify the source for every import. It is still useful if all your files are off disk or if you want to _generate_ a file at run time to be imported by your bundle.

`globals` can absolutely help out with three.js. If you look at the [docs on globals](https://github.com/kentcdodds/mdx-bundler#globals) you can use:

```js
// Bundler
bundleMDX(source, {
  //other options
  globals: {
    '@react-three/fiber': 'reactThreeFiber;
  }
}

// Client
import { Canvas, useFrame } from "@react-three/fiber";

getMDXComponent(result.code, {reactThreeFiber: {Canvas, useFrame}}),
```

The idea is that in your bundle you specify the variable name to import from and then on the client you set that variable name to a value. So above the bundle will actually contain `const {Canvas, useFrame} = reactThreeFiber`.

**Comment by chrislicodes** [comment]
Hi @Arcath, thanks for your answer and sorry for my late reply!

I finally got back to it and I tried out different approaches. Following exactly your suggestion, I added the globals here:

https://github.com/chrislicodes/personal-blog/blob/add-globals/src/mdxTools/mdxServer/index.ts

```ts
export const prepareMDX = async (directoryName: string) => {

 //some other code 

  const { code, frontmatter } = await bundleMDX(source, {

  //other options

    globals: {
      "@react-three/fiber": "reactThreeFiber",
      "@react-three/drei": "reactThreeDrei",
      react: "reactGlobal",
    },
  });

  return { frontmatter, code };
};

```

And the same way as suggested I passed it: 

https://github.com/chrislicodes/personal-blog/blob/add-globals/src/mdxTools/mdxClient/index.tsx

```ts
//import globals
import { Canvas, useFrame } from "@react-three/fiber";
import { Box, OrbitControls } from "@react-three/drei";
import React from "react";

export const MDX: React.FC<{ source: string }> = ({ source }) => {
  const Component = useMemo(
    () =>
      getMDXComponent(source, {
        reactThreeFiber: { Canvas, useFrame },
        reactThreeDrei: { Box, OrbitControls },
        reactGlobal: React,
      }),
    [source]
  );
  return <Component components={{ ...components }} />;
};
```

The error I get is 

```cmd
 errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'No matching export in "global-externals:@react-three/fiber" for import "Canvas"'
    },
```

and same for hte other ones. What am I overseeing here?

https://github.com/chrislicodes/personal-blog/tree/add-globals

**Comment by a7sc11u** [comment]
I am getting the exact same issue, different libraries, but very much the same struggle.

I noticed it's only the named imports that cause the issue. So in @chrislicodes case:

`import {Canvas} from "@react-three/fiber"` : throws the `No matching export in "global-externals` error

but

`import reactThreeFiver from "@react-three/fiber"` is not complaining and works well.

**Comment by a7sc11u** [comment]
@chrislicodes Turns out you need to configure esbuild named-exports.


```
bundleMDX(content, 
  globals: {
    "@react-three/fiber": {
       varName: "reactThreeFiber",
       namedExports: ["Canvas",  "useFrame"],
       defaultExport: false
     }
  }
);
```

https://www.npmjs.com/package/@fal-works/esbuild-plugin-global-externals

**Comment by chrislicodes** [comment]
Everything worked as expected thanks to the previous comment
