### ISSUE TITLE
Improve TypeScript spec for components

### ISSUE THREAD

**Issue by yordis** [kentcdodds/mdx-bundler#91]
- `mdx-bundler` version: 6.0.1
- `node` version: 14.17.3
- `npm` version: 6.14.13

### What you did

```tsx
import * as React from 'react';
import { getMDXComponent } from 'mdx-bundler/client';

type MDXProps = {
  source: string;
  slots?: {
    a?: React.ComponentType<React.PropsWithChildren<{ href: string }>>;
  };
};

export function MDX(props: MDXProps) {
  const Component = React.useMemo(() => getMDXComponent(props.source), [props.source]);
  // @ts-ignore NOTE: This
  return <Component components={props.slots} />;
}
```

### What happened

Reproduction repository:

Working on it on `yordis/add-website` branch

- https://github.com/straw-hat-team/adr/blob/yordis/add-website/website/src/components/mdx/index.tsx

### Problem description:

Notice the existing typespec

![Screen Shot 2021-09-05 at 5 55 14 AM](https://user-images.githubusercontent.com/4237280/132122713-7d9272cc-475d-4716-8c2e-d5d3571983de.png)

### Suggested solution:

Add richer typespec taking into consideration the `components` input. I tried to figure out the full list that `components` take to then figure out the props, would appreciate some direction if you know how to find what I was looking for.

**Comment by dqunbp** [comment]
```typescript
export type ComponentMap = {
    [name: string]: string | React.ComponentType<{}> | ComponentMap;
```

`React.ComponentType<{}>` Breaks ​custom components with props

In my case
```tsx
<Component
  components={{
    a: CustomLink,
    strong: (props: { children?: React.ReactNode; id: string }) => (
      <strong id={props.id}>{props.children}</strong>
    ),
  }}
/>
```

Show an error
```
"(props: { children?: React.ReactNode; id: string; }) => JSX.Element" can't be assigned for "FunctionComponent<{}>".
```
