### ISSUE TITLE
Error when using iFrame in MDX

### ISSUE THREAD

**Issue by city17** [kentcdodds/mdx-bundler#97]
Hi, I'm trying to embed a codesandbox in my MDX file, using an iframe (see code below), but it throws an error. 

Code:

```jsx
  <iframe
  src="https://codesandbox.io/embed/new?codemirror=1"
  style={width:`100%`, height:`500px`, border:`0`, borderRadius: `4px`, overflow:`hidden`}
  allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
  sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
></iframe>
```

Error:

`Error: Error: Build failed with 1 error:
_mdx_bundler_entry_point-e0e682e8-1cdd-4e0e-b01b-e5a93c40df33.mdx:22:14: error: [plugin: esbuild-xdm] Could not parse expression with acorn: Unexpected content after expression`

Any ideas on what might be going wrong here?

- `mdx-bundler` version: 6.01
- `node` version: 14.17.6

**Comment by wooorm** [comment]
That’s not how JSX works, Babel doesn’t parse it either: https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=ATA8EsDMCcEMFsCmAoEBnaBjAvAIgBYAuhADmgFwD0lmA9gCaJqwB29ARrQB4B04tlRPHaJ6lFogDuAfjqN44aNFrRsARlypgaQgE8ANomwBvSeHqF85AAZqADHYCk1gDTB8icAHMiNgKwOJFyuwJzQjNA2diFhEQBKsPTgAK4UwNYALEEhtABuiNCQ-rSSNvjmjCzWAL5asPrFkniwmJiIhspIhAUA3MAI7OCILIQAtPreRKNow2gqfZgIBbB9w5jQuiTd9KNISSvAXoi0xYuE_Cx9XrrKaHQkiH3l9H0K67Qk-LQSr-bgfSRYLokCM-ql2H1ctA-lxoNNAed6qNCHBMABrcAsLyadCsDjcZoNEqjSAqeBofpEyS7Bj1Cn1RqjEgfZJkSmMkjQJjDQiwc7fdnE5hIUYqbyYwXUu7QcBbNCaAB8oEoUDgSAVQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.15.6&externalPlugins=&assumptions=%7B%7D.

Add an extra set of braces around the object
